#!/usr/bin/env bash

REPO_NAME="git-repository-commons"

function main(){
  local cmd="$1"
  local projectFacet="$2"

  importGitUtils "${projectFacet}"

  case "${cmd}" in
    update)
          onGitRootDir update "${projectFacet}"
      ;;
    install)
          onGitRootDir installProjectFacet "${projectFacet}"
          onGitRootDir update "${projectFacet}"
      ;;
    *)
      echo "Usage: $0 {install|update}"
      ;;
  esac
}

function update() {
  local repo="${REPO_NAME}"
  local projectFacet="$1"

  echo "Update project facet ${projectFacet}"

  updateSubtree ${repo} ${projectFacet} .bin
  updateSubtree ${repo} ${projectFacet} .github
}

function install() {
  local repo="${REPO_NAME}"
  local projectFacet="$1"

  echo "Install project facet ${projectFacet}"

  if [ -z "$(git remote | grep "${repo}")" ]; then
    echo "Adding Repository ${repo}"
    git remote add ${repo} https://github.com/link-intersystems/${repo}.git
  fi

  echo "Fetching refs/remotes/${repo}/${projectFacet}/*"
  git fetch ${repo} +refs/heads/${projectFacet}/*:refs/remotes/${repo}/${projectFacet}/*
}


function importGitUtils(){
  local script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

  if [ -f "${script_dir}/git_utils" ]; then
    source "${script_dir}/git_utils"
  else
    # Use git_utils from repository
    local projectFacet="$1"

    local binHead=$(git fetch --porcelain https://github.com/link-intersystems/git-repo-commons.git ${projectFacet}/bin | awk '{ print $3 }')
    local gitUtilsObjectId=$(git ls-tree ${binHead} git_utils | awk '{ print $3 }')

    source <(git cat-file -p ${gitUtilsObjectId})
  fi
}


main "$@"; exit