#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function currentVersion() {
  echo $(gradlewExec properties -q | awk '/^version:/ {print $2}')
}

increment_version() {
  local delimiter=.
  local array=($(echo "$1" | tr $delimiter '\n'))
  array[$2]=$((array[$2]+1))

  for (( j=$(($2+1)); j<${#array[@]}; j++ ));
  do
    array[$j]=0
  done

  echo $(local IFS=$delimiter ; echo "${array[*]}")
}

function findGradlewPath() {
  local rootDir="$(dirname "$SCRIPT_DIR")"
  local gradleWorkdir="$(git rev-parse --show-toplevel)"
  if [ $? == 0 ]; then
      rootDir="${gradleWorkdir}"
  fi
  local gradlew_path="${rootDir}/gradlew"

  echo "${gradlew_path}"
}

function gradlewExec(){
  local gradlew="$(findGradlewPath)"

  if ! [ -f "${gradlew}" ]; then
    >&2 echo "Gradle Wrapper not found: ${gradlew}"
    exit 1
  fi

  if [ -x "${gradlew}" ]; then
    "${gradlew}" "$@"
    return
  fi

  >&2 echo "Gradle Wrapper is not executable: ${gradlew}"
  exit 1
}
