#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

. ${SCRIPT_DIR}/gradlew_utils

RELEASE_STRATEGY="patch"

if [ ! -z "$1" ]; then
  RELEASE_STRATEGY="$1"
  shift
fi

function printHelp(){
   >&2 echo "Usage: $(basename "$0") [patch|minor|major]"
}

shopt -s extglob
case "$RELEASE_STRATEGY" in
      "--help" | "-?" )
        printHelp
      ;;
      "patch" )
        # Nothing to do
      ;;
      "minor" )
        CURRENT_VERSION=$(currentVersion)
        RELEASE_VERSION=$(increment_version ${CURRENT_VERSION} 1)
      ;;
      "major" )
        CURRENT_VERSION=$(currentVersion)
        RELEASE_VERSION=$(increment_version ${CURRENT_VERSION} 0)
      ;;
      +([0-9])?(.+([0-9]))?(.+([0-9])) )
        RELEASE_VERSION="$RELEASE_STRATEGY-SNAPSHOT"
      ;;
      *)
        printHelp
      ;;
esac

echo "Executing ${RELEASE_STRATEGY} release"

source "${SCRIPT_DIR}/gradlew_utils"

if [ ! -z "${RELEASE_VERSION}" ]; then
  gradlewExec --info -Prelease.useAutomaticVersion=true -Prelease.newVersion=${RELEASE_VERSION} :updateVersion :commitNewVersion
else
  gradlewExec --info -Prelease.useAutomaticVersion=true release "$@"
fi

